base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('follow/<str:pk>/', views.add_user_room, name='add_user_room'),
    path('unfollow/<str:pk>/', views.remove_user_room, name='remove_user_room'),
    path('like/<str:pk>/', views.like_room, name='like_room'),
    path('sign-up/', views.registerPage, name='sign_up'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('room/<str:pk>/', views.room, name='room'),
    path('profile/<str:pk>/', views.user_profile, name='user_profile'),
    path('update-user/', views.updateUser, name="update-user"),
    path('profile/follow/<str:pk>/', views.user_follow, name='user_follow'),
    path('profile/unfollow/<str:pk>/', views.user_unfollow, name='user_unfollow'),
    path('create-room/', views.createRoom, name='create_room'),
    path('update-room/<str:pk>/', views.update_room, name='update_room'),
    path('delete-room/<str:pk>/', views.deleteRoom, name='delete_room'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('base.urls', namespace='base')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField

class User(AbstractUser):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    follower = models.ManyToManyField('User', blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    summary = models.CharField(max_length=300)
    image = models.ImageField(upload_to='room/', blank=True, null=True)
    description = RichTextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    like = models.ManyToManyField(User, related_name='like', blank=True)
    views = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['-updated', '-created']

    
    @property
    def getReplies(self):
        return Comment.objects.filter(parent=self).reverse()
    

    @property
    def is_parent(self):
        if self.parent is None:
            return True

    def __str__(self):
        return self.body

templates/component/activity.html
<div class="col-lg-3">
    <nav class="navbar navbar-expand-lg mx-0">
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar">
            <!-- Offcanvas header -->
            <div class="offcanvas-header">
                <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas"
                    aria-label="Close"></button>
            </div>

            <div class="offcanvas-body d-block px-2 px-lg-0">
                <!-- Card START -->
                <div class="card overflow-hidden">
                    <div class="card-header pb-0 border-0">
                        <h5 class="card-title mb-0">Recent Activity (last 30min)</h5>
                    </div>
                    <div class="card-body">
                        {% for comment in comments %}
                        <div class="hstack gap-2 mb-3 bg-light rounded p-2">
                            {% if comment.user.avatar %}
                            <div class="avatar">
                                <img class="avatar-img rounded-circle border border-white border-3"
                                    src="{{comment.user.avatar.url}}" alt="">
                            </div>
                            {% else %}
                            <div class="avatar rounded-circle bg-primary">
                                <h6 class="text-white position-absolute top-50 start-50 translate-middle fw-bold">
                                    <a class="text-white" href="{% url 'base:user_profile' comment.user.id %}">
                                        {% if comment.user.first_name %}
                                        {{comment.user.first_name|first}}{{comment.user.last_name|first}}
                                        {% else %}
                                        {{comment.user.username|first|upper}}
                                        {% endif %}
                                    </a>
                                </h6>
                            </div>
                            {% endif %}
                            <!-- Title -->
                            <div class="overflow-hidden">
                                <div class="d-flex justify-content-between">
                                    <h6 class="mb-1"> <a href="{% url 'base:user_profile' comment.user.id %}"> 
                                        @{{comment.user}} <span class="badge bg-primary bg-opacity-10 text-primary small"> {{comment.created|timesince}}</span>
                                    </a></h6>
                                </div>
                                <p class="small p-1">replyed to group "<a href="{% url 'base:home' %}?q={{comment.room.topic.name}}">{{comment.room.name|truncatewords:3}}</a>"</p>
                                <p class="mb-0 small bg-mode rounded p-2">{{comment.body}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
    </nav>
</div>

templates/component/conversation.html
<div class="offcanvas-body d-block px-2 px-lg-0">
    <!-- Card START -->
    <div class="card overflow-hidden">
        <div class="card-header pb-0 border-0">
            <h5 class="card-title mb-0">Conversations</h5>
        </div>
        <div class="card-body">
            {% for comment in comments %}
            <div class="hstack gap-2 mb-3 bg-light rounded p-2">
                {% if user.avatar %}
                <div class="avatar">
                    <img class="avatar-img rounded-circle border border-white border-3"
                        src="/static/01(1).jpg" alt="">
                </div>
                {% else %}
                <div class="avatar rounded-circle bg-primary">
                    <h6 class="text-white position-absolute top-50 start-50 translate-middle fw-bold">
                        <a class="text-white" href="{% url 'base:user_profile' comment.user.id %}">
                            {% if comment.user.first_name %}
                            {{comment.user.first_name|first}}{{comment.user.last_name|first}}
                            {% else %}
                            {{comment.user.username|first|upper}}
                            {% endif %}
                        </a>
                    </h6>
                </div>
                {% endif %}
                <!-- Title -->
                <div class="overflow-hidden">
                    <div class="d-flex justify-content-between">
                        <h6 class="mb-1"> <a href="{% url 'base:user_profile' comment.user.id %}"> 
                            @{{comment.user}} <span class="badge bg-primary bg-opacity-10 text-primary small"> {{comment.created|timesince}}</span>
                        </a></h6>
                    </div>
                    <p class="mb-0 small bg-light rounded p-2">{{comment.body}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/component/feed.html
{% for room in rooms %}
<div id="post" class="card">
    <!-- Card header START -->
    <div class="card-header border-0 pb-0">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <div>
                    <h6 class="card-title mb-0"> <a class="pro-link" href="{% url 'base:room' room.id %}"> {{room.name|truncatewords:10}} </a></h6>
                    <div class="nav nav-divider">
                        <p class="nav-item mb-0 small mt-1"><a href="{% url 'base:user_profile' room.host.id %}">@{{room.host.username}}</a></p>
                        <span class="nav-item small"> {{room.created|date:"D d M Y"}}</span>
                    </div>
                </div>
            </div>
            <!-- Card share action START -->
            <div class="dropdown">
                <span class="small badge bg-primary">
                    <a class="text-white" 
                    href="{% if request.user in room.participants.all %}{% url 'base:remove_user_room' room.id %}{% else %}{% url 'base:add_user_room' room.id %}{% endif %}"> 
                    {% if request.user in room.participants.all %} Following {% else %} Follow {% endif %}
                    </a>
                </span>
            </div>
            <!-- Card share action END -->
        </div>
    </div>
    <!-- Card header START -->
    <!-- Card body START -->
    <div class="card-body">
        <p>{{room.summary}}</p>
        <!-- Card feed grid START -->
        {% if room.image %}
        <div class="d-flex justify-content-between">
            <div class="row">
                <center>
                    <div class="col-7">

                        <a class="h-100" href="{% url 'base:room' room.id %}">
                            <img class="rounded img-fluid" src="{{room.image.url}}" alt="Image">
                        </a>
                    </div>
                </center>
            </div>
        </div>
        {% endif %}
        

        <ul class="nav nav-pills nav-pills-light nav-fill nav-stack small py-1 mt-3">
            <li class="nav-item">
                <a class="nav-link mb-0 active p-2" href="{% url 'base:home' %}?q={{room.topic.name}}">{{room.topic.name|title}}. Followers {{room.participants.all.count}}</a>
            </li>
            <!-- Card share action menu START -->
            <li class="nav-item dropdown">
                <a href="{% url 'base:room' room.id %}" class="nav-link mb-0">
                    <i class="bi bi-heart-fill"></i> {{room.like.all.count}}
                </a>
            </li>
            {% if request.user == room.host %}
            <li class="nav-item">
                <a class="pro-link btn btn-warning" href="{% url 'base:update_room' room.id %}">Update</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link mb-0" href="{% url 'base:room' room.id %}"> <i class="bi bi-chat-fill pe-1"></i> {{room.comment_set.all.count}}</a>
            </li>
        </ul>
    </div>
</div>
{% endfor %}

templates/component/topics.html
{% if url_name == 'home' or url_name == 'user_profile' %}
<div class="col-lg-3">
    <nav class="navbar navbar-expand-lg mx-0">
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasSideNavbar">
            <!-- Offcanvas header -->
            <div class="offcanvas-header">
                <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas"
                    aria-label="Close"></button>
            </div>

            <!-- Offcanvas body -->
            <div class="offcanvas-body d-block px-2 px-lg-0">
                <!-- Card START -->
                <div class="card overflow-hidden">
                    <div class="card-header pb-0 border-0">
                        <center>
                            <h5 class="card-title mb-0"><a class="btn btn-primary-soft" href="{% url 'base:home' %}">
                                    All Languages <span>{{topics.count}}</span></a></h5>
                        </center>
                    </div>
                    <div class="card-body">
                        {% for topic in topics %}
                        <div class="hstack gap-2 bg-body rounded p-2">
                            <div class="overflow-hidden">
                                <a class="h6 mb-0" href="{% url 'base:home' %}?q={{topic.name}}">{{topic.name}} </a>
                                <p class="mb-0 small text-truncate">{{topic.room_set.all.count}} rooms available</p>
                            </div>
                            <a class="btn btn-primary-soft rounded-circle icon-md ms-auto"
                                href="{% url 'base:home' %}?q={{topic.name}}"><i class="fa-solid fa-plus"> </i></a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
{% endif %}