base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('follow/<str:pk>/', views.add_user_room, name='add_user_room'),
    path('unfollow/<str:pk>/', views.remove_user_room, name='remove_user_room'),
    path('like/<str:pk>/', views.like_room, name='like_room'),
    path('sign-up/', views.registerPage, name='sign_up'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('room/<str:pk>/', views.room, name='room'),
    path('profile/<str:pk>/', views.user_profile, name='user_profile'),
    path('update-user/', views.updateUser, name="update-user"),
    path('profile/follow/<str:pk>/', views.user_follow, name='user_follow'),
    path('profile/unfollow/<str:pk>/', views.user_unfollow, name='user_unfollow'),
    path('create-room/', views.createRoom, name='create_room'),
    path('update-room/<str:pk>/', views.update_room, name='update_room'),
    path('delete-room/<str:pk>/', views.deleteRoom, name='delete_room'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('base.urls', namespace='base')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField

class User(AbstractUser):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    follower = models.ManyToManyField('User', blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    summary = models.CharField(max_length=300)
    image = models.ImageField(upload_to='room/', blank=True, null=True)
    description = RichTextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    like = models.ManyToManyField(User, related_name='like', blank=True)
    views = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['-updated', '-created']

    
    @property
    def getReplies(self):
        return Comment.objects.filter(parent=self).reverse()
    

    @property
    def is_parent(self):
        if self.parent is None:
            return True

    def __str__(self):
        return self.body

base/forms.py
from django.forms import ModelForm, TextInput
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from .models import Room, User, Comment


class MyUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'summary', 'participants', 'like', 'views']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'username', 'email', 'first_name', 'last_name']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body','parent']
        widgets = {
            'body' : TextInput(),
        }

base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import resolve
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Topic, Room, Comment, User
from .forms import RoomForm, MyUserCreationForm, UserForm, CommentForm
from django.utils import timezone
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {
        'page': page,
    }
    return render(request, 'registration/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('base:home')

def registerge(request):
    page = 'Sign Up'
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'An error occurred during registration')

    context = {
        'form': form,
        'page': page,
    }
    return render(request, 'registration/login.html', context)


def registerPage(request):
    page = 'Sign Up'
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created! You can now log in.')
            return redirect('base:login')

    else:
        form = MyUserCreationForm()

    context = {
        'form': form,
        'page': page,
    }
    return render(request, 'registration/login.html', context)



@login_required(login_url='login')
def updateUser(request):
    page = 'User Update'

    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('base:user_profile', pk=user.id)
        else:
            messages.error(request, 'This username was already used')

    return render(request, 'registration/update-user.html', {'form': form, 'page': page,})


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)                        
    )
    room_count = rooms.count()
    topics = Topic.objects.all()

    now = timezone.now()
    last = now - timezone.timedelta(minutes=30)
    comments = Comment.objects.filter(Q(room__topic__name__icontains=q)).filter(created__gte=last)

    context = {
        'rooms': rooms,
        'topics': topics,
        'room_count': room_count,
        'q': q,
        'comments': comments,
    }

    return render(request, 'home.html', context)

def room(request, pk):
    room = get_object_or_404(Room, id=pk)
    comments = room.comment_set.all().order_by('-created')
    comments_count = comments.count()
    participants = room.participants.all()
    
    if room:
        room.views = room.views + 1
        room.save()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            body = comment_form.cleaned_data['body']
            try:
                parent = comment_form.cleaned_data['parent']
            except:
                parent=None

        new_comment = Comment(body=body, user=request.user, room=room, parent=parent)
        new_comment.save()
        return redirect('base:room', pk=room.id)
    else:
        comment_form = CommentForm()

    context = {
        'room': room,
        'comment_form': comment_form,
        'comments': comments,
        'comments_count': comments_count,
        'participants': participants,
    }

    return render(request, 'room.html', context)



def user_profile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    comments = user.comment_set.all()
    topics = Topic.objects.all()
    connection = rooms.count() + comments.count()

    context = {
        'user': user,
        'rooms': rooms,
        'comments': comments,
        'topics': topics,
        'connection': connection,
    }
    return render(request, 'profile.html', context)


@login_required(login_url='base:login')
def user_follow(request, pk):
    if request.user:
        request_user = request.user
        user = User.objects.get(id=pk)

        user.follower.add(request_user)
        user.save()

        return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'profile.html')


@login_required(login_url='base:login')
def user_unfollow(request, pk):
    if request.user:
        request_user = request.user
        user = User.objects.get(id=pk)

        user.follower.remove(request_user)
        user.save()

        return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'home.html')


@login_required(login_url='base:login')
def createRoom(request):
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.host = request.user
            post.save()
        return redirect('base:home')
    else:
        form = RoomForm()

    topics = Topic.objects.all()
    title = 'Create'
    context = {
        'form':form,
        'title': title,
        'topics': topics,
    }

    return render(request, 'room_create.html', context)


@csrf_exempt
@login_required(login_url='base:login')
def update_room(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    title = 'Update'

    if request.user == room.host:
        if request.method == 'POST':
            form = RoomForm(request.POST, instance=room)
            if form.is_valid():
                form.save()

                return HttpResponse("OK")
        else:return render(request, 'room_form.html', {'form':form, 'room':room, 'title':title,})  
    else:return HttpResponse('You are not allowed here')
    

@login_required(login_url='base:login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('You are not allowed here')

    if request.method == 'POST':
        room.delete()
        return redirect('base:home')

    context = {
        'room':room,
    }

    return render(request, 'delete_room.html', context)


def page_name(request):
    url_name = resolve(request.path).url_name
    return {'url_name': url_name}


@login_required(login_url='base:login')
def add_user_room(request, pk):
    if request.user:
        user = request.user
        room = Room.objects.get(id=pk)

        room.participants.add(user)
        room.save()

        return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'home.html')


@login_required(login_url='base:login')
def remove_user_room(request, pk):
    if request.user:
        user = request.user
        room = Room.objects.get(id=pk)

        room.participants.remove(user)
        room.save()

        return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'home.html')



@login_required(login_url='base:login')
def like_room(request, pk):
    if request.user:
        user = request.user
        room = Room.objects.get(id=pk)

        room.like.add(user)
        room.save()

        return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'home.html')

templates/delete_room.html
{% extends 'base.html' %}
{% block title %}Delete Room{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Container START -->
<div class="container">
    <div class="row g-4">
        <h4>Delete room</h4>

        <form method="post" action="">
            {% csrf_token %}
            <p>Are you sure you wanna delete {{room}}?</p>
            <a href="{% url 'base:home' %}">Go back.</a>
            {{form|crispy }}

            <input class="btn btn-sm btn-primary-soft" type="submit" value="submit" />
        </form>
    </div>
</div>


{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row g-4">

        {% include 'component/topics.html' %}

        <div class="col-lg-6 vstack gap-4">
            <!-- Card START -->
            <div class="card">
                <div class="h-200px rounded-top"
                    style="background-image:url(/media/01\(1\).jpg); background-position: center; background-size: cover; background-repeat: no-repeat;">
                </div>
                <!-- Card body START -->
                <div class="card-body py-0">
                    <div class="d-sm-flex align-items-start text-center text-sm-start">
                        <div>
                            {% if user.avatar %}
                            <div class="avatar avatar-xxl mt-n5 mb-3">
                                <img class="avatar-img rounded-circle border border-white border-3"
                                    src="{{user.avatar.url}}" alt="">
                            </div>
                            {% else %}
                            <div class="avatar avatar-xxl mt-n5 mb-3 rounded-circle bg-primary">
                                <h3 class="text-white position-absolute top-50 start-50 translate-middle fw-bold">
                                    {% if user.first_name %}
                                    {{user.first_name|first}}{{user.last_name|first}}
                                    {% else %}
                                    {{user.username|first|upper}}
                                    {% endif %}
                                </h3>
                            </div>
                            {% endif %}
                        </div>
                        <div class="ms-sm-4 mt-sm-3">
                            <!-- Info -->
                            <h1 class="mb-0 h5">{% if user.first_name %}{{user.first_name|title}}
                                {{user.last_name|title}}{% else %}{{user.username|title}}{% endif %} 
                                {% if request.user == user %}
                                <a href="{% url 'base:update-user' %}" class="btn btn--main btn--pill">
                                    <i class="bi bi-pen-fill text-primary small"></i></a>
                                {% endif %}
                            </h1>
                            <small></small>
                            <p>{{connection}} connections
                            </p>
                        </div>
                    </div>
                    <!-- List profile -->
                    <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
                        {% if request.user.id != user.id %}
                        <li class="list-inline-item">
                            <a class="btn-primary-soft rounded p-1"
                                href="{% if request.user in user.follower.all %}{% url 'base:user_unfollow' user.id %}{% else %}{% url 'base:user_follow' user.id %}{% endif %}">
                                <i class="bi bi-person-fill-add"></i> {% if request.user in user.follower.all %} Following {% else %} Follow {% endif %}
                            </a>
                        </li>
                        {% endif %}
                        <li class="list-inline-item">

                            <a class="btn-primary-soft rounded p-1" data-bs-toggle="modal"
                                data-bs-target="#exampleModal">
                                <i class="bi bi-people-fill"></i> Followers
                            </a>


                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Followers</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">

                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="card">
                                                        <div class="table-responsive">
                                                            {% if user.follower.all %}
                                                            <table class="table table-flush" id="datatable-search">
                                                                <tbody>
                                                                    {% for follower in user.follower.all %}
                                                                    <tr>
                                                                        <td class="text-xs font-weight-bold p-3">
                                                                            <div class="d-flex align-items-center">
                                                                                {% if follower.avatar %}
                                                                                <a class="nav-link icon-md p-0" href="{% url 'base:user_profile' follower.id %}">
                                                                                    <img class="avatar-img rounded-2 me-3"
                                                                                        src="{{ follower.avatar.url }}" alt="">
                                                                                </a>
                                                                                {% else %}
                                                                                <a class="nav-link icon-md p-0 me-3"
                                                                                    href="{% url 'base:user_profile' follower.id %}">
                                                                                    <div
                                                                                        class="avatar-img avatar rounded-circle bg-primary me-2">
                                                                                        <h6
                                                                                            class="text-white position-absolute top-50 start-50 translate-middle fw-bold">
                                                                                            {% if follower.first_name %}
                                                                                            {{follower.first_name|first}}{{follower.last_name|first}}
                                                                                            {% else %}
                                                                                            {{follower.username|first|upper}}
                                                                                            {% endif %}
                                                                                        </h6>
                                                                                    </div>
                                                                                </a>
                                                                                {% endif %}
                                                                                <span><a
                                                                                        href="{% url 'base:user_profile' follower.id %}">
                                                                                        {% if follower.first_name %}
                                                                                        {{follower.first_name}} {{follower.last_name}}
                                                                                        {% else %}
                                                                                        {{follower.username|title}}
                                                                                        {% endif %}</a>
                                                                                    <i class="bi bi-patch-check-fill text-primary small"></i>
                                                                                </span>
                                                                            </div>
                                                                        </td>
                                                                    </tr>
                                                                    {% endfor %}
                                                                </tbody>
                                                            </table>
                                                            {% else %}
                                                            <h6 class="p-3">You don't have follower yet</h6>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="list-inline-item mt-2"><i class="bi bi-calendar2-plus me-1"></i> {{user.date_joined}}
                        </li>
                    </ul>
                </div>
                <!-- Card body END -->
                <div class="card-footer mt-3 pt-2 pb-0">
                    <!-- Nav profile pages -->
                    <ul
                        class="nav nav-bottom-line align-items-center justify-content-center justify-content-md-start mb-0 border-0">
                        <li class="nav-item"> <a class="nav-link" href="{% url 'base:user_profile' user.id %}"> Activity
                                <span class="badge bg-success bg-opacity-10 text-success small">
                                    {{user.room_set.all.count}}</span></a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{% url 'base:create_room' %}"> Create Room</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Card END -->

            {% include 'component/feed.html' %}

        </div>

        {% include 'component/activity.html' %}

    </div>
</div>
{% endblock %}

templates/profile_conversation.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row g-4">

        {% include 'component/topics.html' %}

        <div class="col-lg-6 vstack gap-4">
            <!-- Card START -->
            <div class="card">
                <div class="h-200px rounded-top"
                    style="background-image:url(/media/01\(1\).jpg); background-position: center; background-size: cover; background-repeat: no-repeat;">
                </div>
                <!-- Card body START -->
                <div class="card-body py-0">
                    <div class="d-sm-flex align-items-start text-center text-sm-start">
                        <div>
                            {% if user.avatar %}
                            <div class="avatar avatar-xxl mt-n5 mb-3">
                                <img class="avatar-img rounded-circle border border-white border-3"
                                    src="/static/01(1).jpg" alt="">
                            </div>
                            {% else %}
                            <div class="avatar avatar-xxl mt-n5 mb-3 rounded-circle bg-primary">
                                <h3 class="text-white position-absolute top-50 start-50 translate-middle fw-bold">
                                    {% if user.first_name %}
                                    {{user.first_name|first}}{{user.last_name|first}}
                                    {% else %}
                                    {{user.username|first|upper}}
                                    {% endif %}
                                </h3>
                            </div>
                            {% endif %}
                        </div>
                        <div class="ms-sm-4 mt-sm-3">
                            <!-- Info -->
                            <h1 class="mb-0 h5">{% if user.first_name %}{{user.first_name|title}}
                                {{user.last_name|title}}{% else %}{{user.username|title}}{% endif %} <i
                                    class="bi bi-patch-check-fill text-success small"></i>
                            </h1>
                            <small></small>
                            <p><span class="badge bg-primary me-3">@{{user.username}}</span> 250 connections</p>
                        </div>
                    </div>
                    <!-- List profile -->
                    <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
                        <li class="list-inline-item"><i class="bi bi-briefcase me-1"></i> Lead Developer</li>
                        <li class="list-inline-item"><i class="bi bi-geo-alt me-1"></i> New Hampshire</li>
                        <li class="list-inline-item"><i class="bi bi-calendar2-plus me-1"></i> Joined on Nov 26, 2019
                        </li>
                    </ul>
                </div>
                <!-- Card body END -->
                <div class="card-footer mt-3 pt-2 pb-0">
                    <!-- Nav profile pages -->
                    <ul
                        class="nav nav-bottom-line align-items-center justify-content-center justify-content-md-start mb-0 border-0">
                        <li class="nav-item"> <a class="nav-link" href=""> Activity <span
                            class="badge bg-success bg-opacity-10 text-success small"> {{user.room_set.all.count}}</span></a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{% url 'base:conversation' user.id %}"> Connections <span
                                    class="badge bg-success bg-opacity-10 text-success small"> {{user.comment_set.all.count}}</span> </a> </li>
                        <li class="nav-item"> <a class="nav-link" href="{% url 'base:create_room' %}"> Create Room</a> </li>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Card END -->

            {% include 'component/conversation.html' %}

        </div>

        {% include 'component/activity.html' %}

    </div>
</div>
{% endblock %}

templates/room_create.html
{% extends 'base.html' %}
{% block title %}{{title}} Room{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="col-md-8 col-lg-12 p-5">
    <!-- Create a page START -->
    <div class="card">
        <!-- Title START -->
        <div class="card-header border-0 pb-0">
            <h1 class="h4 card-title mb-0">Create a page</h1>
        </div>
        <!-- Title END -->
        <!-- Create a page form START -->
        <div class="card-body">
            <form id="article-form" action="{% url 'base:create_room' %}" method="post">
                {{form|crispy}}
                <button id="submitButton1" data-redirect="{% url 'base:create_room' %}"  type="button" class="btn btn-primary" >Submit</button>
            </form>
        </div>
        <!-- Create a page form END -->
    </div>
    <!-- Create a page END -->
</div>


{% endblock %}

templates/room_form.html
{% extends 'base.html' %}
{% block title %}{{title}} Room{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="col-md-8 col-lg-12 p-5">
    <!-- Create a page START -->
    <div class="card">
        <!-- Title START -->
        <div class="card-header border-0 pb-0">
            <h1 class="h4 card-title mb-0">Create a page</h1>
        </div>
        <!-- Title END -->
        <!-- Create a page form START -->
        <div class="card-body">
            <form id="article-form" action="{% url 'base:update_room' room.id %}" method="post">
                {{form|crispy}}
                <button id="submitButton1" data-redirect="{% url 'base:update_room' room.id %}"  type="button" class="btn btn-primary" >Submit</button>
            </form>
        </div>
        <!-- Create a page form END -->
    </div>
    <!-- Create a page END -->
</div>


{% endblock %}